-- Migration 001: transaction_features table
-- Stores derived features for the hedonic model
-- Idempotent: safe to re-run (uses IF NOT EXISTS / CREATE OR REPLACE)

CREATE TABLE IF NOT EXISTS transaction_features (
    id                      SERIAL PRIMARY KEY,
    clean_id                INTEGER NOT NULL REFERENCES transactions_clean(id) ON DELETE CASCADE,

    -- Price features (price_features.py)
    gap_pct                 NUMERIC(10, 6),     -- Winsorized (1-99%): (real - calc) / calc
    gap_pct_raw             NUMERIC(10, 6),     -- Raw, unclipped
    price_percentile_25     NUMERIC(10, 4),     -- p25 UF/m² by (project_type, county_name, year)
    price_percentile_50     NUMERIC(10, 4),     -- p50 (median)
    price_percentile_75     NUMERIC(10, 4),     -- p75
    price_vs_median         NUMERIC(8, 4),      -- uf_m2_building / p50 ratio (>1 = above median)

    -- Spatial features (spatial_features.py)
    dist_km_centroid        NUMERIC(8, 4),      -- Distance in km to commune centroid (EPSG:32719)
    cluster_id              INTEGER,            -- DBSCAN cluster label (-1 = noise)

    -- Temporal features (temporal_features.py)
    quarter_q1              SMALLINT,           -- Dummy: 1 if Q1
    quarter_q2              SMALLINT,
    quarter_q3              SMALLINT,
    quarter_q4              SMALLINT,
    season_index            NUMERIC(4, 3),      -- (quarter - 1) / 3.0 → [0.0, 0.333, 0.667, 1.0]

    computed_at             TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT uq_tf_clean_id UNIQUE (clean_id)
);

CREATE INDEX IF NOT EXISTS idx_tf_clean_id    ON transaction_features(clean_id);
CREATE INDEX IF NOT EXISTS idx_tf_gap_pct     ON transaction_features(gap_pct ASC);
CREATE INDEX IF NOT EXISTS idx_tf_cluster     ON transaction_features(cluster_id);

COMMENT ON TABLE transaction_features IS
  'Derived features for hedonic model. Regenerated by build_features.py (TRUNCATE + reload). Do not edit manually.';
